#print("Roar!...")
#print("Meow!....")
#print("İbrahim")
#print("Hello World!")
#print("Teyzemi çok seviyorum")
#print("The itsy bitsy spider climbed up the waterspoot.")
#print()
#print("Down came the rain and washed the spider out.")
#print("My", "name", "is", "Monty", "Python.", sep="-")
print('hello world')
